version: '3.8'

services:
  lodestone_core:
    image: ghcr.io/SelfHostedHub/lodestone_core
    ports:
      - "16662:16662"
    volumes:
      - ./lodestone_core:/home/user/.lodestone/
    user: "${PUID}:${PGID}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}